# Generated by Django 4.1.7 on 2023-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
