# Generated by Django 4.1.7 on 2023-03-22 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_auto_20230227_1752'),
        ('reviews', '0002_alter_reviews_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='ProductReviews',
        ),
    ]
