# Generated by Django 3.2.17 on 2023-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230226_1601'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='variant',
            field=models.ManyToManyField(blank=True, to='products.Variant'),
        ),
    ]
