# Generated by Django 4.1.7 on 2023-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
