# Generated by Django 4.1.7 on 2023-03-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_voucher_is_active_voucher_max_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
