# Generated by Django 4.1.7 on 2023-03-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartitems_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='user',
        ),
    ]
