# Generated by Django 4.1.7 on 2023-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_voucher_cart_remove_voucher_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_value',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
