# Generated by Django 4.1.7 on 2023-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_voucher_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], max_length=1000, null=True),
        ),
    ]
