# Generated by Django 4.1.7 on 2023-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_voucher_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
