# Generated by Django 3.2.17 on 2023-03-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Item'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'Payment'},
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='status',
            new_name='payment_choice',
        ),
    ]
