# Generated by Django 4.1.7 on 2023-03-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230304_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_choice',
        ),
    ]
