# Generated by Django 3.2.17 on 2023-02-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variant_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Color'), (2, 'Size')], null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='varinat_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
