# Generated by Django 3.2.17 on 2023-02-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230226_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='varinat_value',
            new_name='variant_value',
        ),
    ]
