# Generated by Django 3.2.17 on 2023-02-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_varinat_value_variant_variant_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='variant_type',
            field=models.CharField(blank=True, choices=[('Color', 'Color'), ('Size', 'Size')], max_length=200, null=True),
        ),
    ]
