# Generated by Django 3.2.17 on 2023-02-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_variant_variant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='title',
        ),
    ]
